apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: GitTix
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: diogo96/git-tix_auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "dist/***/*.js"
            dest: .
    - image: diogo96/git-tix_ticket-service
      context: ticket-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "dist/***/*.js"
            dest: .
    - image: diogo96/git-tix_orders-service
      context: orders-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "dist/***/*.js"
            dest: .
    - image: diogo96/git-tix-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "***/*.js"
            dest: .
